//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import Rswift
import UIKit

/// This `R` struct is generated and contains references to static resources.
struct R: Rswift.Validatable {
  fileprivate static let applicationLocale = hostingBundle.preferredLocalizations.first.flatMap(Locale.init) ?? Locale.current
  fileprivate static let hostingBundle = Bundle(for: R.Class.self)

  /// Find first language and bundle for which the table exists
  fileprivate static func localeBundle(tableName: String, preferredLanguages: [String]) -> (Foundation.Locale, Foundation.Bundle)? {
    // Filter preferredLanguages to localizations, use first locale
    var languages = preferredLanguages
      .map(Locale.init)
      .prefix(1)
      .flatMap { locale -> [String] in
        if hostingBundle.localizations.contains(locale.identifier) {
          if let language = locale.languageCode, hostingBundle.localizations.contains(language) {
            return [locale.identifier, language]
          } else {
            return [locale.identifier]
          }
        } else if let language = locale.languageCode, hostingBundle.localizations.contains(language) {
          return [language]
        } else {
          return []
        }
      }

    // If there's no languages, use development language as backstop
    if languages.isEmpty {
      if let developmentLocalization = hostingBundle.developmentLocalization {
        languages = [developmentLocalization]
      }
    } else {
      // Insert Base as second item (between locale identifier and languageCode)
      languages.insert("Base", at: 1)

      // Add development language as backstop
      if let developmentLocalization = hostingBundle.developmentLocalization {
        languages.append(developmentLocalization)
      }
    }

    // Find first language for which table exists
    // Note: key might not exist in chosen language (in that case, key will be shown)
    for language in languages {
      if let lproj = hostingBundle.url(forResource: language, withExtension: "lproj"),
         let lbundle = Bundle(url: lproj)
      {
        let strings = lbundle.url(forResource: tableName, withExtension: "strings")
        let stringsdict = lbundle.url(forResource: tableName, withExtension: "stringsdict")

        if strings != nil || stringsdict != nil {
          return (Locale(identifier: language), lbundle)
        }
      }
    }

    // If table is available in main bundle, don't look for localized resources
    let strings = hostingBundle.url(forResource: tableName, withExtension: "strings", subdirectory: nil, localization: nil)
    let stringsdict = hostingBundle.url(forResource: tableName, withExtension: "stringsdict", subdirectory: nil, localization: nil)

    if strings != nil || stringsdict != nil {
      return (applicationLocale, hostingBundle)
    }

    // If table is not found for requested languages, key will be shown
    return nil
  }

  /// Load string from Info.plist file
  fileprivate static func infoPlistString(path: [String], key: String) -> String? {
    var dict = hostingBundle.infoDictionary
    for step in path {
      guard let obj = dict?[step] as? [String: Any] else { return nil }
      dict = obj
    }
    return dict?[key] as? String
  }

  static func validate() throws {
    try intern.validate()
  }

  #if os(iOS) || os(tvOS)
  /// This `R.storyboard` struct is generated, and contains static references to 3 storyboards.
  struct storyboard {
    /// Storyboard `EBSetting`.
    static let ebSetting = _R.storyboard.ebSetting()
    /// Storyboard `EBWeather`.
    static let ebWeather = _R.storyboard.ebWeather()
    /// Storyboard `LaunchScreen`.
    static let launchScreen = _R.storyboard.launchScreen()

    #if os(iOS) || os(tvOS)
    /// `UIStoryboard(name: "EBSetting", bundle: ...)`
    static func ebSetting(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.ebSetting)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIStoryboard(name: "EBWeather", bundle: ...)`
    static func ebWeather(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.ebWeather)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIStoryboard(name: "LaunchScreen", bundle: ...)`
    static func launchScreen(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.launchScreen)
    }
    #endif

    fileprivate init() {}
  }
  #endif

  /// This `R.color` struct is generated, and contains static references to 0 colors.
  struct color {
    /// This `R.color.background` struct is generated, and contains static references to 6 colors.
    struct background {
      /// Color `background`.
      static let background = Rswift.ColorResource(bundle: R.hostingBundle, name: "background/background")
      /// Color `error`.
      static let error = Rswift.ColorResource(bundle: R.hostingBundle, name: "background/error")
      /// Color `primary_heavy_20`.
      static let primary_heavy_20 = Rswift.ColorResource(bundle: R.hostingBundle, name: "background/primary_heavy_20")
      /// Color `primary`.
      static let primary = Rswift.ColorResource(bundle: R.hostingBundle, name: "background/primary")
      /// Color `secondary`.
      static let secondary = Rswift.ColorResource(bundle: R.hostingBundle, name: "background/secondary")
      /// Color `surface`.
      static let surface = Rswift.ColorResource(bundle: R.hostingBundle, name: "background/surface")

      #if os(iOS) || os(tvOS)
      /// `UIColor(named: "background", bundle: ..., traitCollection: ...)`
      @available(tvOS 11.0, *)
      @available(iOS 11.0, *)
      static func background(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
        return UIKit.UIColor(resource: R.color.background.background, compatibleWith: traitCollection)
      }
      #endif

      #if os(iOS) || os(tvOS)
      /// `UIColor(named: "error", bundle: ..., traitCollection: ...)`
      @available(tvOS 11.0, *)
      @available(iOS 11.0, *)
      static func error(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
        return UIKit.UIColor(resource: R.color.background.error, compatibleWith: traitCollection)
      }
      #endif

      #if os(iOS) || os(tvOS)
      /// `UIColor(named: "primary", bundle: ..., traitCollection: ...)`
      @available(tvOS 11.0, *)
      @available(iOS 11.0, *)
      static func primary(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
        return UIKit.UIColor(resource: R.color.background.primary, compatibleWith: traitCollection)
      }
      #endif

      #if os(iOS) || os(tvOS)
      /// `UIColor(named: "primary_heavy_20", bundle: ..., traitCollection: ...)`
      @available(tvOS 11.0, *)
      @available(iOS 11.0, *)
      static func primary_heavy_20(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
        return UIKit.UIColor(resource: R.color.background.primary_heavy_20, compatibleWith: traitCollection)
      }
      #endif

      #if os(iOS) || os(tvOS)
      /// `UIColor(named: "secondary", bundle: ..., traitCollection: ...)`
      @available(tvOS 11.0, *)
      @available(iOS 11.0, *)
      static func secondary(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
        return UIKit.UIColor(resource: R.color.background.secondary, compatibleWith: traitCollection)
      }
      #endif

      #if os(iOS) || os(tvOS)
      /// `UIColor(named: "surface", bundle: ..., traitCollection: ...)`
      @available(tvOS 11.0, *)
      @available(iOS 11.0, *)
      static func surface(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
        return UIKit.UIColor(resource: R.color.background.surface, compatibleWith: traitCollection)
      }
      #endif

      fileprivate init() {}
    }

    /// This `R.color.text` struct is generated, and contains static references to 5 colors.
    struct text {
      /// Color `on_background`.
      static let on_background = Rswift.ColorResource(bundle: R.hostingBundle, name: "text/on_background")
      /// Color `on_error`.
      static let on_error = Rswift.ColorResource(bundle: R.hostingBundle, name: "text/on_error")
      /// Color `on_primary`.
      static let on_primary = Rswift.ColorResource(bundle: R.hostingBundle, name: "text/on_primary")
      /// Color `on_secondary`.
      static let on_secondary = Rswift.ColorResource(bundle: R.hostingBundle, name: "text/on_secondary")
      /// Color `on_surface`.
      static let on_surface = Rswift.ColorResource(bundle: R.hostingBundle, name: "text/on_surface")

      #if os(iOS) || os(tvOS)
      /// `UIColor(named: "on_background", bundle: ..., traitCollection: ...)`
      @available(tvOS 11.0, *)
      @available(iOS 11.0, *)
      static func on_background(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
        return UIKit.UIColor(resource: R.color.text.on_background, compatibleWith: traitCollection)
      }
      #endif

      #if os(iOS) || os(tvOS)
      /// `UIColor(named: "on_error", bundle: ..., traitCollection: ...)`
      @available(tvOS 11.0, *)
      @available(iOS 11.0, *)
      static func on_error(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
        return UIKit.UIColor(resource: R.color.text.on_error, compatibleWith: traitCollection)
      }
      #endif

      #if os(iOS) || os(tvOS)
      /// `UIColor(named: "on_primary", bundle: ..., traitCollection: ...)`
      @available(tvOS 11.0, *)
      @available(iOS 11.0, *)
      static func on_primary(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
        return UIKit.UIColor(resource: R.color.text.on_primary, compatibleWith: traitCollection)
      }
      #endif

      #if os(iOS) || os(tvOS)
      /// `UIColor(named: "on_secondary", bundle: ..., traitCollection: ...)`
      @available(tvOS 11.0, *)
      @available(iOS 11.0, *)
      static func on_secondary(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
        return UIKit.UIColor(resource: R.color.text.on_secondary, compatibleWith: traitCollection)
      }
      #endif

      #if os(iOS) || os(tvOS)
      /// `UIColor(named: "on_surface", bundle: ..., traitCollection: ...)`
      @available(tvOS 11.0, *)
      @available(iOS 11.0, *)
      static func on_surface(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
        return UIKit.UIColor(resource: R.color.text.on_surface, compatibleWith: traitCollection)
      }
      #endif

      fileprivate init() {}
    }

    fileprivate init() {}
  }

  /// This `R.image` struct is generated, and contains static references to 0 images.
  struct image {
    /// This `R.image.icon` struct is generated, and contains static references to 0 images.
    struct icon {
      /// This `R.image.icon.action` struct is generated, and contains static references to 6 images.
      struct action {
        /// Image `navigation_circle_filled`.
        static let navigation_circle_filled = Rswift.ImageResource(bundle: R.hostingBundle, name: "icon/action/navigation_circle_filled")
        /// Image `navigation_circle`.
        static let navigation_circle = Rswift.ImageResource(bundle: R.hostingBundle, name: "icon/action/navigation_circle")
        /// Image `plus_circle_filled`.
        static let plus_circle_filled = Rswift.ImageResource(bundle: R.hostingBundle, name: "icon/action/plus_circle_filled")
        /// Image `plus_circle`.
        static let plus_circle = Rswift.ImageResource(bundle: R.hostingBundle, name: "icon/action/plus_circle")
        /// Image `synchronize_circle_filled`.
        static let synchronize_circle_filled = Rswift.ImageResource(bundle: R.hostingBundle, name: "icon/action/synchronize_circle_filled")
        /// Image `synchronize_circle`.
        static let synchronize_circle = Rswift.ImageResource(bundle: R.hostingBundle, name: "icon/action/synchronize_circle")

        #if os(iOS) || os(tvOS)
        /// `UIImage(named: "navigation_circle", bundle: ..., traitCollection: ...)`
        static func navigation_circle(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
          return UIKit.UIImage(resource: R.image.icon.action.navigation_circle, compatibleWith: traitCollection)
        }
        #endif

        #if os(iOS) || os(tvOS)
        /// `UIImage(named: "navigation_circle_filled", bundle: ..., traitCollection: ...)`
        static func navigation_circle_filled(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
          return UIKit.UIImage(resource: R.image.icon.action.navigation_circle_filled, compatibleWith: traitCollection)
        }
        #endif

        #if os(iOS) || os(tvOS)
        /// `UIImage(named: "plus_circle", bundle: ..., traitCollection: ...)`
        static func plus_circle(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
          return UIKit.UIImage(resource: R.image.icon.action.plus_circle, compatibleWith: traitCollection)
        }
        #endif

        #if os(iOS) || os(tvOS)
        /// `UIImage(named: "plus_circle_filled", bundle: ..., traitCollection: ...)`
        static func plus_circle_filled(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
          return UIKit.UIImage(resource: R.image.icon.action.plus_circle_filled, compatibleWith: traitCollection)
        }
        #endif

        #if os(iOS) || os(tvOS)
        /// `UIImage(named: "synchronize_circle", bundle: ..., traitCollection: ...)`
        static func synchronize_circle(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
          return UIKit.UIImage(resource: R.image.icon.action.synchronize_circle, compatibleWith: traitCollection)
        }
        #endif

        #if os(iOS) || os(tvOS)
        /// `UIImage(named: "synchronize_circle_filled", bundle: ..., traitCollection: ...)`
        static func synchronize_circle_filled(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
          return UIKit.UIImage(resource: R.image.icon.action.synchronize_circle_filled, compatibleWith: traitCollection)
        }
        #endif

        fileprivate init() {}
      }

      /// This `R.image.icon.general` struct is generated, and contains static references to 10 images.
      struct general {
        /// Image `cross_filled`.
        static let cross_filled = Rswift.ImageResource(bundle: R.hostingBundle, name: "icon/general/cross_filled")
        /// Image `cross`.
        static let cross = Rswift.ImageResource(bundle: R.hostingBundle, name: "icon/general/cross")
        /// Image `gear_filled`.
        static let gear_filled = Rswift.ImageResource(bundle: R.hostingBundle, name: "icon/general/gear_filled")
        /// Image `gear`.
        static let gear = Rswift.ImageResource(bundle: R.hostingBundle, name: "icon/general/gear")
        /// Image `pin_filled`.
        static let pin_filled = Rswift.ImageResource(bundle: R.hostingBundle, name: "icon/general/pin_filled")
        /// Image `pin`.
        static let pin = Rswift.ImageResource(bundle: R.hostingBundle, name: "icon/general/pin")
        /// Image `wet_filled`.
        static let wet_filled = Rswift.ImageResource(bundle: R.hostingBundle, name: "icon/general/wet_filled")
        /// Image `wet`.
        static let wet = Rswift.ImageResource(bundle: R.hostingBundle, name: "icon/general/wet")
        /// Image `wind_filled`.
        static let wind_filled = Rswift.ImageResource(bundle: R.hostingBundle, name: "icon/general/wind_filled")
        /// Image `wind`.
        static let wind = Rswift.ImageResource(bundle: R.hostingBundle, name: "icon/general/wind")

        #if os(iOS) || os(tvOS)
        /// `UIImage(named: "cross", bundle: ..., traitCollection: ...)`
        static func cross(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
          return UIKit.UIImage(resource: R.image.icon.general.cross, compatibleWith: traitCollection)
        }
        #endif

        #if os(iOS) || os(tvOS)
        /// `UIImage(named: "cross_filled", bundle: ..., traitCollection: ...)`
        static func cross_filled(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
          return UIKit.UIImage(resource: R.image.icon.general.cross_filled, compatibleWith: traitCollection)
        }
        #endif

        #if os(iOS) || os(tvOS)
        /// `UIImage(named: "gear", bundle: ..., traitCollection: ...)`
        static func gear(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
          return UIKit.UIImage(resource: R.image.icon.general.gear, compatibleWith: traitCollection)
        }
        #endif

        #if os(iOS) || os(tvOS)
        /// `UIImage(named: "gear_filled", bundle: ..., traitCollection: ...)`
        static func gear_filled(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
          return UIKit.UIImage(resource: R.image.icon.general.gear_filled, compatibleWith: traitCollection)
        }
        #endif

        #if os(iOS) || os(tvOS)
        /// `UIImage(named: "pin", bundle: ..., traitCollection: ...)`
        static func pin(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
          return UIKit.UIImage(resource: R.image.icon.general.pin, compatibleWith: traitCollection)
        }
        #endif

        #if os(iOS) || os(tvOS)
        /// `UIImage(named: "pin_filled", bundle: ..., traitCollection: ...)`
        static func pin_filled(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
          return UIKit.UIImage(resource: R.image.icon.general.pin_filled, compatibleWith: traitCollection)
        }
        #endif

        #if os(iOS) || os(tvOS)
        /// `UIImage(named: "wet", bundle: ..., traitCollection: ...)`
        static func wet(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
          return UIKit.UIImage(resource: R.image.icon.general.wet, compatibleWith: traitCollection)
        }
        #endif

        #if os(iOS) || os(tvOS)
        /// `UIImage(named: "wet_filled", bundle: ..., traitCollection: ...)`
        static func wet_filled(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
          return UIKit.UIImage(resource: R.image.icon.general.wet_filled, compatibleWith: traitCollection)
        }
        #endif

        #if os(iOS) || os(tvOS)
        /// `UIImage(named: "wind", bundle: ..., traitCollection: ...)`
        static func wind(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
          return UIKit.UIImage(resource: R.image.icon.general.wind, compatibleWith: traitCollection)
        }
        #endif

        #if os(iOS) || os(tvOS)
        /// `UIImage(named: "wind_filled", bundle: ..., traitCollection: ...)`
        static func wind_filled(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
          return UIKit.UIImage(resource: R.image.icon.general.wind_filled, compatibleWith: traitCollection)
        }
        #endif

        fileprivate init() {}
      }

      /// This `R.image.icon.weather` struct is generated, and contains static references to 44 images.
      struct weather {
        /// Image `clear_day_filled`.
        static let clear_day_filled = Rswift.ImageResource(bundle: R.hostingBundle, name: "icon/weather/clear_day_filled")
        /// Image `clear_day`.
        static let clear_day = Rswift.ImageResource(bundle: R.hostingBundle, name: "icon/weather/clear_day")
        /// Image `clear_night_filled`.
        static let clear_night_filled = Rswift.ImageResource(bundle: R.hostingBundle, name: "icon/weather/clear_night_filled")
        /// Image `clear_night`.
        static let clear_night = Rswift.ImageResource(bundle: R.hostingBundle, name: "icon/weather/clear_night")
        /// Image `cloud_dash_filled`.
        static let cloud_dash_filled = Rswift.ImageResource(bundle: R.hostingBundle, name: "icon/weather/cloud_dash_filled")
        /// Image `cloud_dash`.
        static let cloud_dash = Rswift.ImageResource(bundle: R.hostingBundle, name: "icon/weather/cloud_dash")
        /// Image `cloud_error_filled`.
        static let cloud_error_filled = Rswift.ImageResource(bundle: R.hostingBundle, name: "icon/weather/cloud_error_filled")
        /// Image `cloud_error`.
        static let cloud_error = Rswift.ImageResource(bundle: R.hostingBundle, name: "icon/weather/cloud_error")
        /// Image `cloudy_day_filled`.
        static let cloudy_day_filled = Rswift.ImageResource(bundle: R.hostingBundle, name: "icon/weather/cloudy_day_filled")
        /// Image `cloudy_day`.
        static let cloudy_day = Rswift.ImageResource(bundle: R.hostingBundle, name: "icon/weather/cloudy_day")
        /// Image `cloudy_filled`.
        static let cloudy_filled = Rswift.ImageResource(bundle: R.hostingBundle, name: "icon/weather/cloudy_filled")
        /// Image `cloudy_heavy_filled`.
        static let cloudy_heavy_filled = Rswift.ImageResource(bundle: R.hostingBundle, name: "icon/weather/cloudy_heavy_filled")
        /// Image `cloudy_heavy`.
        static let cloudy_heavy = Rswift.ImageResource(bundle: R.hostingBundle, name: "icon/weather/cloudy_heavy")
        /// Image `cloudy_night_filled`.
        static let cloudy_night_filled = Rswift.ImageResource(bundle: R.hostingBundle, name: "icon/weather/cloudy_night_filled")
        /// Image `cloudy_night`.
        static let cloudy_night = Rswift.ImageResource(bundle: R.hostingBundle, name: "icon/weather/cloudy_night")
        /// Image `cloudy`.
        static let cloudy = Rswift.ImageResource(bundle: R.hostingBundle, name: "icon/weather/cloudy")
        /// Image `drizzle_filled`.
        static let drizzle_filled = Rswift.ImageResource(bundle: R.hostingBundle, name: "icon/weather/drizzle_filled")
        /// Image `drizzle_heavy_filled`.
        static let drizzle_heavy_filled = Rswift.ImageResource(bundle: R.hostingBundle, name: "icon/weather/drizzle_heavy_filled")
        /// Image `drizzle_heavy`.
        static let drizzle_heavy = Rswift.ImageResource(bundle: R.hostingBundle, name: "icon/weather/drizzle_heavy")
        /// Image `drizzle_light_filled`.
        static let drizzle_light_filled = Rswift.ImageResource(bundle: R.hostingBundle, name: "icon/weather/drizzle_light_filled")
        /// Image `drizzle_light`.
        static let drizzle_light = Rswift.ImageResource(bundle: R.hostingBundle, name: "icon/weather/drizzle_light")
        /// Image `drizzle`.
        static let drizzle = Rswift.ImageResource(bundle: R.hostingBundle, name: "icon/weather/drizzle")
        /// Image `fog_day_filled`.
        static let fog_day_filled = Rswift.ImageResource(bundle: R.hostingBundle, name: "icon/weather/fog_day_filled")
        /// Image `fog_day`.
        static let fog_day = Rswift.ImageResource(bundle: R.hostingBundle, name: "icon/weather/fog_day")
        /// Image `fog_night_filled`.
        static let fog_night_filled = Rswift.ImageResource(bundle: R.hostingBundle, name: "icon/weather/fog_night_filled")
        /// Image `fog_night`.
        static let fog_night = Rswift.ImageResource(bundle: R.hostingBundle, name: "icon/weather/fog_night")
        /// Image `rain_filled`.
        static let rain_filled = Rswift.ImageResource(bundle: R.hostingBundle, name: "icon/weather/rain_filled")
        /// Image `rain_heavy_filled`.
        static let rain_heavy_filled = Rswift.ImageResource(bundle: R.hostingBundle, name: "icon/weather/rain_heavy_filled")
        /// Image `rain_heavy`.
        static let rain_heavy = Rswift.ImageResource(bundle: R.hostingBundle, name: "icon/weather/rain_heavy")
        /// Image `rain_light_filled`.
        static let rain_light_filled = Rswift.ImageResource(bundle: R.hostingBundle, name: "icon/weather/rain_light_filled")
        /// Image `rain_light`.
        static let rain_light = Rswift.ImageResource(bundle: R.hostingBundle, name: "icon/weather/rain_light")
        /// Image `rain`.
        static let rain = Rswift.ImageResource(bundle: R.hostingBundle, name: "icon/weather/rain")
        /// Image `snow_heavy_filled`.
        static let snow_heavy_filled = Rswift.ImageResource(bundle: R.hostingBundle, name: "icon/weather/snow_heavy_filled")
        /// Image `snow_heavy`.
        static let snow_heavy = Rswift.ImageResource(bundle: R.hostingBundle, name: "icon/weather/snow_heavy")
        /// Image `snow_light_filled`.
        static let snow_light_filled = Rswift.ImageResource(bundle: R.hostingBundle, name: "icon/weather/snow_light_filled")
        /// Image `snow_light`.
        static let snow_light = Rswift.ImageResource(bundle: R.hostingBundle, name: "icon/weather/snow_light")
        /// Image `storm_heavy_filled`.
        static let storm_heavy_filled = Rswift.ImageResource(bundle: R.hostingBundle, name: "icon/weather/storm_heavy_filled")
        /// Image `storm_heavy`.
        static let storm_heavy = Rswift.ImageResource(bundle: R.hostingBundle, name: "icon/weather/storm_heavy")
        /// Image `storm_light_filled`.
        static let storm_light_filled = Rswift.ImageResource(bundle: R.hostingBundle, name: "icon/weather/storm_light_filled")
        /// Image `storm_light`.
        static let storm_light = Rswift.ImageResource(bundle: R.hostingBundle, name: "icon/weather/storm_light")
        /// Image `storm_rain_filled`.
        static let storm_rain_filled = Rswift.ImageResource(bundle: R.hostingBundle, name: "icon/weather/storm_rain_filled")
        /// Image `storm_rain`.
        static let storm_rain = Rswift.ImageResource(bundle: R.hostingBundle, name: "icon/weather/storm_rain")
        /// Image `tornado_filled`.
        static let tornado_filled = Rswift.ImageResource(bundle: R.hostingBundle, name: "icon/weather/tornado_filled")
        /// Image `tornado`.
        static let tornado = Rswift.ImageResource(bundle: R.hostingBundle, name: "icon/weather/tornado")

        #if os(iOS) || os(tvOS)
        /// `UIImage(named: "clear_day", bundle: ..., traitCollection: ...)`
        static func clear_day(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
          return UIKit.UIImage(resource: R.image.icon.weather.clear_day, compatibleWith: traitCollection)
        }
        #endif

        #if os(iOS) || os(tvOS)
        /// `UIImage(named: "clear_day_filled", bundle: ..., traitCollection: ...)`
        static func clear_day_filled(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
          return UIKit.UIImage(resource: R.image.icon.weather.clear_day_filled, compatibleWith: traitCollection)
        }
        #endif

        #if os(iOS) || os(tvOS)
        /// `UIImage(named: "clear_night", bundle: ..., traitCollection: ...)`
        static func clear_night(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
          return UIKit.UIImage(resource: R.image.icon.weather.clear_night, compatibleWith: traitCollection)
        }
        #endif

        #if os(iOS) || os(tvOS)
        /// `UIImage(named: "clear_night_filled", bundle: ..., traitCollection: ...)`
        static func clear_night_filled(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
          return UIKit.UIImage(resource: R.image.icon.weather.clear_night_filled, compatibleWith: traitCollection)
        }
        #endif

        #if os(iOS) || os(tvOS)
        /// `UIImage(named: "cloud_dash", bundle: ..., traitCollection: ...)`
        static func cloud_dash(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
          return UIKit.UIImage(resource: R.image.icon.weather.cloud_dash, compatibleWith: traitCollection)
        }
        #endif

        #if os(iOS) || os(tvOS)
        /// `UIImage(named: "cloud_dash_filled", bundle: ..., traitCollection: ...)`
        static func cloud_dash_filled(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
          return UIKit.UIImage(resource: R.image.icon.weather.cloud_dash_filled, compatibleWith: traitCollection)
        }
        #endif

        #if os(iOS) || os(tvOS)
        /// `UIImage(named: "cloud_error", bundle: ..., traitCollection: ...)`
        static func cloud_error(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
          return UIKit.UIImage(resource: R.image.icon.weather.cloud_error, compatibleWith: traitCollection)
        }
        #endif

        #if os(iOS) || os(tvOS)
        /// `UIImage(named: "cloud_error_filled", bundle: ..., traitCollection: ...)`
        static func cloud_error_filled(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
          return UIKit.UIImage(resource: R.image.icon.weather.cloud_error_filled, compatibleWith: traitCollection)
        }
        #endif

        #if os(iOS) || os(tvOS)
        /// `UIImage(named: "cloudy", bundle: ..., traitCollection: ...)`
        static func cloudy(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
          return UIKit.UIImage(resource: R.image.icon.weather.cloudy, compatibleWith: traitCollection)
        }
        #endif

        #if os(iOS) || os(tvOS)
        /// `UIImage(named: "cloudy_day", bundle: ..., traitCollection: ...)`
        static func cloudy_day(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
          return UIKit.UIImage(resource: R.image.icon.weather.cloudy_day, compatibleWith: traitCollection)
        }
        #endif

        #if os(iOS) || os(tvOS)
        /// `UIImage(named: "cloudy_day_filled", bundle: ..., traitCollection: ...)`
        static func cloudy_day_filled(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
          return UIKit.UIImage(resource: R.image.icon.weather.cloudy_day_filled, compatibleWith: traitCollection)
        }
        #endif

        #if os(iOS) || os(tvOS)
        /// `UIImage(named: "cloudy_filled", bundle: ..., traitCollection: ...)`
        static func cloudy_filled(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
          return UIKit.UIImage(resource: R.image.icon.weather.cloudy_filled, compatibleWith: traitCollection)
        }
        #endif

        #if os(iOS) || os(tvOS)
        /// `UIImage(named: "cloudy_heavy", bundle: ..., traitCollection: ...)`
        static func cloudy_heavy(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
          return UIKit.UIImage(resource: R.image.icon.weather.cloudy_heavy, compatibleWith: traitCollection)
        }
        #endif

        #if os(iOS) || os(tvOS)
        /// `UIImage(named: "cloudy_heavy_filled", bundle: ..., traitCollection: ...)`
        static func cloudy_heavy_filled(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
          return UIKit.UIImage(resource: R.image.icon.weather.cloudy_heavy_filled, compatibleWith: traitCollection)
        }
        #endif

        #if os(iOS) || os(tvOS)
        /// `UIImage(named: "cloudy_night", bundle: ..., traitCollection: ...)`
        static func cloudy_night(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
          return UIKit.UIImage(resource: R.image.icon.weather.cloudy_night, compatibleWith: traitCollection)
        }
        #endif

        #if os(iOS) || os(tvOS)
        /// `UIImage(named: "cloudy_night_filled", bundle: ..., traitCollection: ...)`
        static func cloudy_night_filled(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
          return UIKit.UIImage(resource: R.image.icon.weather.cloudy_night_filled, compatibleWith: traitCollection)
        }
        #endif

        #if os(iOS) || os(tvOS)
        /// `UIImage(named: "drizzle", bundle: ..., traitCollection: ...)`
        static func drizzle(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
          return UIKit.UIImage(resource: R.image.icon.weather.drizzle, compatibleWith: traitCollection)
        }
        #endif

        #if os(iOS) || os(tvOS)
        /// `UIImage(named: "drizzle_filled", bundle: ..., traitCollection: ...)`
        static func drizzle_filled(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
          return UIKit.UIImage(resource: R.image.icon.weather.drizzle_filled, compatibleWith: traitCollection)
        }
        #endif

        #if os(iOS) || os(tvOS)
        /// `UIImage(named: "drizzle_heavy", bundle: ..., traitCollection: ...)`
        static func drizzle_heavy(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
          return UIKit.UIImage(resource: R.image.icon.weather.drizzle_heavy, compatibleWith: traitCollection)
        }
        #endif

        #if os(iOS) || os(tvOS)
        /// `UIImage(named: "drizzle_heavy_filled", bundle: ..., traitCollection: ...)`
        static func drizzle_heavy_filled(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
          return UIKit.UIImage(resource: R.image.icon.weather.drizzle_heavy_filled, compatibleWith: traitCollection)
        }
        #endif

        #if os(iOS) || os(tvOS)
        /// `UIImage(named: "drizzle_light", bundle: ..., traitCollection: ...)`
        static func drizzle_light(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
          return UIKit.UIImage(resource: R.image.icon.weather.drizzle_light, compatibleWith: traitCollection)
        }
        #endif

        #if os(iOS) || os(tvOS)
        /// `UIImage(named: "drizzle_light_filled", bundle: ..., traitCollection: ...)`
        static func drizzle_light_filled(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
          return UIKit.UIImage(resource: R.image.icon.weather.drizzle_light_filled, compatibleWith: traitCollection)
        }
        #endif

        #if os(iOS) || os(tvOS)
        /// `UIImage(named: "fog_day", bundle: ..., traitCollection: ...)`
        static func fog_day(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
          return UIKit.UIImage(resource: R.image.icon.weather.fog_day, compatibleWith: traitCollection)
        }
        #endif

        #if os(iOS) || os(tvOS)
        /// `UIImage(named: "fog_day_filled", bundle: ..., traitCollection: ...)`
        static func fog_day_filled(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
          return UIKit.UIImage(resource: R.image.icon.weather.fog_day_filled, compatibleWith: traitCollection)
        }
        #endif

        #if os(iOS) || os(tvOS)
        /// `UIImage(named: "fog_night", bundle: ..., traitCollection: ...)`
        static func fog_night(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
          return UIKit.UIImage(resource: R.image.icon.weather.fog_night, compatibleWith: traitCollection)
        }
        #endif

        #if os(iOS) || os(tvOS)
        /// `UIImage(named: "fog_night_filled", bundle: ..., traitCollection: ...)`
        static func fog_night_filled(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
          return UIKit.UIImage(resource: R.image.icon.weather.fog_night_filled, compatibleWith: traitCollection)
        }
        #endif

        #if os(iOS) || os(tvOS)
        /// `UIImage(named: "rain", bundle: ..., traitCollection: ...)`
        static func rain(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
          return UIKit.UIImage(resource: R.image.icon.weather.rain, compatibleWith: traitCollection)
        }
        #endif

        #if os(iOS) || os(tvOS)
        /// `UIImage(named: "rain_filled", bundle: ..., traitCollection: ...)`
        static func rain_filled(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
          return UIKit.UIImage(resource: R.image.icon.weather.rain_filled, compatibleWith: traitCollection)
        }
        #endif

        #if os(iOS) || os(tvOS)
        /// `UIImage(named: "rain_heavy", bundle: ..., traitCollection: ...)`
        static func rain_heavy(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
          return UIKit.UIImage(resource: R.image.icon.weather.rain_heavy, compatibleWith: traitCollection)
        }
        #endif

        #if os(iOS) || os(tvOS)
        /// `UIImage(named: "rain_heavy_filled", bundle: ..., traitCollection: ...)`
        static func rain_heavy_filled(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
          return UIKit.UIImage(resource: R.image.icon.weather.rain_heavy_filled, compatibleWith: traitCollection)
        }
        #endif

        #if os(iOS) || os(tvOS)
        /// `UIImage(named: "rain_light", bundle: ..., traitCollection: ...)`
        static func rain_light(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
          return UIKit.UIImage(resource: R.image.icon.weather.rain_light, compatibleWith: traitCollection)
        }
        #endif

        #if os(iOS) || os(tvOS)
        /// `UIImage(named: "rain_light_filled", bundle: ..., traitCollection: ...)`
        static func rain_light_filled(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
          return UIKit.UIImage(resource: R.image.icon.weather.rain_light_filled, compatibleWith: traitCollection)
        }
        #endif

        #if os(iOS) || os(tvOS)
        /// `UIImage(named: "snow_heavy", bundle: ..., traitCollection: ...)`
        static func snow_heavy(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
          return UIKit.UIImage(resource: R.image.icon.weather.snow_heavy, compatibleWith: traitCollection)
        }
        #endif

        #if os(iOS) || os(tvOS)
        /// `UIImage(named: "snow_heavy_filled", bundle: ..., traitCollection: ...)`
        static func snow_heavy_filled(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
          return UIKit.UIImage(resource: R.image.icon.weather.snow_heavy_filled, compatibleWith: traitCollection)
        }
        #endif

        #if os(iOS) || os(tvOS)
        /// `UIImage(named: "snow_light", bundle: ..., traitCollection: ...)`
        static func snow_light(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
          return UIKit.UIImage(resource: R.image.icon.weather.snow_light, compatibleWith: traitCollection)
        }
        #endif

        #if os(iOS) || os(tvOS)
        /// `UIImage(named: "snow_light_filled", bundle: ..., traitCollection: ...)`
        static func snow_light_filled(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
          return UIKit.UIImage(resource: R.image.icon.weather.snow_light_filled, compatibleWith: traitCollection)
        }
        #endif

        #if os(iOS) || os(tvOS)
        /// `UIImage(named: "storm_heavy", bundle: ..., traitCollection: ...)`
        static func storm_heavy(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
          return UIKit.UIImage(resource: R.image.icon.weather.storm_heavy, compatibleWith: traitCollection)
        }
        #endif

        #if os(iOS) || os(tvOS)
        /// `UIImage(named: "storm_heavy_filled", bundle: ..., traitCollection: ...)`
        static func storm_heavy_filled(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
          return UIKit.UIImage(resource: R.image.icon.weather.storm_heavy_filled, compatibleWith: traitCollection)
        }
        #endif

        #if os(iOS) || os(tvOS)
        /// `UIImage(named: "storm_light", bundle: ..., traitCollection: ...)`
        static func storm_light(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
          return UIKit.UIImage(resource: R.image.icon.weather.storm_light, compatibleWith: traitCollection)
        }
        #endif

        #if os(iOS) || os(tvOS)
        /// `UIImage(named: "storm_light_filled", bundle: ..., traitCollection: ...)`
        static func storm_light_filled(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
          return UIKit.UIImage(resource: R.image.icon.weather.storm_light_filled, compatibleWith: traitCollection)
        }
        #endif

        #if os(iOS) || os(tvOS)
        /// `UIImage(named: "storm_rain", bundle: ..., traitCollection: ...)`
        static func storm_rain(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
          return UIKit.UIImage(resource: R.image.icon.weather.storm_rain, compatibleWith: traitCollection)
        }
        #endif

        #if os(iOS) || os(tvOS)
        /// `UIImage(named: "storm_rain_filled", bundle: ..., traitCollection: ...)`
        static func storm_rain_filled(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
          return UIKit.UIImage(resource: R.image.icon.weather.storm_rain_filled, compatibleWith: traitCollection)
        }
        #endif

        #if os(iOS) || os(tvOS)
        /// `UIImage(named: "tornado", bundle: ..., traitCollection: ...)`
        static func tornado(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
          return UIKit.UIImage(resource: R.image.icon.weather.tornado, compatibleWith: traitCollection)
        }
        #endif

        #if os(iOS) || os(tvOS)
        /// `UIImage(named: "tornado_filled", bundle: ..., traitCollection: ...)`
        static func tornado_filled(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
          return UIKit.UIImage(resource: R.image.icon.weather.tornado_filled, compatibleWith: traitCollection)
        }
        #endif

        fileprivate init() {}
      }

      fileprivate init() {}
    }

    fileprivate init() {}
  }

  /// This `R.nib` struct is generated, and contains static references to 3 nibs.
  struct nib {
    /// Nib `EBRequestErrorEmptySetView`.
    static let ebRequestErrorEmptySetView = _R.nib._EBRequestErrorEmptySetView()
    /// Nib `EBWeatherListEmptySetView`.
    static let ebWeatherListEmptySetView = _R.nib._EBWeatherListEmptySetView()
    /// Nib `EBWeatherListItemCell`.
    static let ebWeatherListItemCell = _R.nib._EBWeatherListItemCell()

    #if os(iOS) || os(tvOS)
    /// `UINib(name: "EBRequestErrorEmptySetView", in: bundle)`
    @available(*, deprecated, message: "Use UINib(resource: R.nib.ebRequestErrorEmptySetView) instead")
    static func ebRequestErrorEmptySetView(_: Void = ()) -> UIKit.UINib {
      return UIKit.UINib(resource: R.nib.ebRequestErrorEmptySetView)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UINib(name: "EBWeatherListEmptySetView", in: bundle)`
    @available(*, deprecated, message: "Use UINib(resource: R.nib.ebWeatherListEmptySetView) instead")
    static func ebWeatherListEmptySetView(_: Void = ()) -> UIKit.UINib {
      return UIKit.UINib(resource: R.nib.ebWeatherListEmptySetView)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UINib(name: "EBWeatherListItemCell", in: bundle)`
    @available(*, deprecated, message: "Use UINib(resource: R.nib.ebWeatherListItemCell) instead")
    static func ebWeatherListItemCell(_: Void = ()) -> UIKit.UINib {
      return UIKit.UINib(resource: R.nib.ebWeatherListItemCell)
    }
    #endif

    static func ebRequestErrorEmptySetView(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> EBRequestErrorEmptySetView? {
      return R.nib.ebRequestErrorEmptySetView.instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? EBRequestErrorEmptySetView
    }

    static func ebWeatherListEmptySetView(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> EBWeatherListEmptySetView? {
      return R.nib.ebWeatherListEmptySetView.instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? EBWeatherListEmptySetView
    }

    static func ebWeatherListItemCell(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> EBWeatherListItemCell? {
      return R.nib.ebWeatherListItemCell.instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? EBWeatherListItemCell
    }

    fileprivate init() {}
  }

  /// This `R.string` struct is generated, and contains static references to 2 localization tables.
  struct string {
    /// This `R.string.launchScreen` struct is generated, and contains static references to 0 localization keys.
    struct launchScreen {
      fileprivate init() {}
    }

    /// This `R.string.localizable` struct is generated, and contains static references to 6 localization keys.
    struct localizable {
      /// en translation: Dark
      ///
      /// Locales: en, zh-Hans, zh-Hant
      static let setting_value_dark = Rswift.StringResource(key: "setting_value_dark", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "zh-Hans", "zh-Hant"], comment: nil)
      /// en translation: Icons by
      ///
      /// Locales: en, zh-Hans, zh-Hant
      static let setting_title_icon = Rswift.StringResource(key: "setting_title_icon", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "zh-Hans", "zh-Hant"], comment: nil)
      /// en translation: Language
      ///
      /// Locales: en, zh-Hans, zh-Hant
      static let setting_title_language = Rswift.StringResource(key: "setting_title_language", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "zh-Hans", "zh-Hant"], comment: nil)
      /// en translation: Light
      ///
      /// Locales: en, zh-Hans, zh-Hant
      static let setting_value_light = Rswift.StringResource(key: "setting_value_light", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "zh-Hans", "zh-Hant"], comment: nil)
      /// en translation: Settings
      ///
      /// Locales: en, zh-Hans, zh-Hant
      static let setting_title = Rswift.StringResource(key: "setting_title", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "zh-Hans", "zh-Hant"], comment: nil)
      /// en translation: Theme
      ///
      /// Locales: en, zh-Hans, zh-Hant
      static let setting_title_theme = Rswift.StringResource(key: "setting_title_theme", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en", "zh-Hans", "zh-Hant"], comment: nil)

      /// en translation: Dark
      ///
      /// Locales: en, zh-Hans, zh-Hant
      static func setting_value_dark(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("setting_value_dark", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "setting_value_dark"
        }

        return NSLocalizedString("setting_value_dark", bundle: bundle, comment: "")
      }

      /// en translation: Icons by
      ///
      /// Locales: en, zh-Hans, zh-Hant
      static func setting_title_icon(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("setting_title_icon", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "setting_title_icon"
        }

        return NSLocalizedString("setting_title_icon", bundle: bundle, comment: "")
      }

      /// en translation: Language
      ///
      /// Locales: en, zh-Hans, zh-Hant
      static func setting_title_language(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("setting_title_language", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "setting_title_language"
        }

        return NSLocalizedString("setting_title_language", bundle: bundle, comment: "")
      }

      /// en translation: Light
      ///
      /// Locales: en, zh-Hans, zh-Hant
      static func setting_value_light(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("setting_value_light", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "setting_value_light"
        }

        return NSLocalizedString("setting_value_light", bundle: bundle, comment: "")
      }

      /// en translation: Settings
      ///
      /// Locales: en, zh-Hans, zh-Hant
      static func setting_title(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("setting_title", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "setting_title"
        }

        return NSLocalizedString("setting_title", bundle: bundle, comment: "")
      }

      /// en translation: Theme
      ///
      /// Locales: en, zh-Hans, zh-Hant
      static func setting_title_theme(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("setting_title_theme", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "setting_title_theme"
        }

        return NSLocalizedString("setting_title_theme", bundle: bundle, comment: "")
      }

      fileprivate init() {}
    }

    fileprivate init() {}
  }

  fileprivate struct intern: Rswift.Validatable {
    fileprivate static func validate() throws {
      try _R.validate()
    }

    fileprivate init() {}
  }

  fileprivate class Class {}

  fileprivate init() {}
}

struct _R: Rswift.Validatable {
  static func validate() throws {
    #if os(iOS) || os(tvOS)
    try nib.validate()
    #endif
    #if os(iOS) || os(tvOS)
    try storyboard.validate()
    #endif
  }

  #if os(iOS) || os(tvOS)
  struct nib: Rswift.Validatable {
    static func validate() throws {
      try _EBRequestErrorEmptySetView.validate()
      try _EBWeatherListEmptySetView.validate()
      try _EBWeatherListItemCell.validate()
    }

    struct _EBRequestErrorEmptySetView: Rswift.NibResourceType, Rswift.Validatable {
      let bundle = R.hostingBundle
      let name = "EBRequestErrorEmptySetView"

      func firstView(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> EBRequestErrorEmptySetView? {
        return instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? EBRequestErrorEmptySetView
      }

      static func validate() throws {
        if UIKit.UIImage(named: "icon/action/synchronize_circle", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'icon/action/synchronize_circle' is used in nib 'EBRequestErrorEmptySetView', but couldn't be loaded.") }
        if UIKit.UIImage(named: "icon/action/synchronize_circle_filled", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'icon/action/synchronize_circle_filled' is used in nib 'EBRequestErrorEmptySetView', but couldn't be loaded.") }
        if UIKit.UIImage(named: "icon/weather/cloud_error", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'icon/weather/cloud_error' is used in nib 'EBRequestErrorEmptySetView', but couldn't be loaded.") }
        if UIKit.UIImage(named: "icon/weather/cloud_error_filled", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'icon/weather/cloud_error_filled' is used in nib 'EBRequestErrorEmptySetView', but couldn't be loaded.") }
        if #available(iOS 11.0, tvOS 11.0, *) {
        }
      }

      fileprivate init() {}
    }

    struct _EBWeatherListEmptySetView: Rswift.NibResourceType, Rswift.Validatable {
      let bundle = R.hostingBundle
      let name = "EBWeatherListEmptySetView"

      func firstView(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> EBWeatherListEmptySetView? {
        return instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? EBWeatherListEmptySetView
      }

      static func validate() throws {
        if UIKit.UIImage(named: "icon/action/synchronize_circle", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'icon/action/synchronize_circle' is used in nib 'EBWeatherListEmptySetView', but couldn't be loaded.") }
        if UIKit.UIImage(named: "icon/action/synchronize_circle_filled", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'icon/action/synchronize_circle_filled' is used in nib 'EBWeatherListEmptySetView', but couldn't be loaded.") }
        if UIKit.UIImage(named: "icon/weather/cloud_dash", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'icon/weather/cloud_dash' is used in nib 'EBWeatherListEmptySetView', but couldn't be loaded.") }
        if UIKit.UIImage(named: "icon/weather/cloud_dash_filled", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'icon/weather/cloud_dash_filled' is used in nib 'EBWeatherListEmptySetView', but couldn't be loaded.") }
        if #available(iOS 11.0, tvOS 11.0, *) {
        }
      }

      fileprivate init() {}
    }

    struct _EBWeatherListItemCell: Rswift.NibResourceType, Rswift.Validatable {
      let bundle = R.hostingBundle
      let name = "EBWeatherListItemCell"

      func firstView(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> EBWeatherListItemCell? {
        return instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? EBWeatherListItemCell
      }

      static func validate() throws {
        if UIKit.UIImage(named: "image/icon/weather/cloud-dash", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'image/icon/weather/cloud-dash' is used in nib 'EBWeatherListItemCell', but couldn't be loaded.") }
        if UIKit.UIImage(named: "image/icon/weather/cloud-dash-filled", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'image/icon/weather/cloud-dash-filled' is used in nib 'EBWeatherListItemCell', but couldn't be loaded.") }
        if #available(iOS 11.0, tvOS 11.0, *) {
        }
      }

      fileprivate init() {}
    }

    fileprivate init() {}
  }
  #endif

  #if os(iOS) || os(tvOS)
  struct storyboard: Rswift.Validatable {
    static func validate() throws {
      #if os(iOS) || os(tvOS)
      try ebSetting.validate()
      #endif
      #if os(iOS) || os(tvOS)
      try ebWeather.validate()
      #endif
      #if os(iOS) || os(tvOS)
      try launchScreen.validate()
      #endif
    }

    #if os(iOS) || os(tvOS)
    struct ebSetting: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = EBSettingRootViewController

      let bundle = R.hostingBundle
      let ebSettingRootViewController = StoryboardViewControllerResource<EBSettingRootViewController>(identifier: "EBSettingRootViewController")
      let name = "EBSetting"

      func ebSettingRootViewController(_: Void = ()) -> EBSettingRootViewController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: ebSettingRootViewController)
      }

      static func validate() throws {
        if UIKit.UIImage(named: "image/icon/general/cross", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'image/icon/general/cross' is used in storyboard 'EBSetting', but couldn't be loaded.") }
        if UIKit.UIImage(named: "image/icon/general/cross-filled", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'image/icon/general/cross-filled' is used in storyboard 'EBSetting', but couldn't be loaded.") }
        if #available(iOS 11.0, tvOS 11.0, *) {
          if UIKit.UIColor(named: "color/background/background", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Color named 'color/background/background' is used in storyboard 'EBSetting', but couldn't be loaded.") }
          if UIKit.UIColor(named: "color/background/primary", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Color named 'color/background/primary' is used in storyboard 'EBSetting', but couldn't be loaded.") }
          if UIKit.UIColor(named: "color/text/on-background", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Color named 'color/text/on-background' is used in storyboard 'EBSetting', but couldn't be loaded.") }
        }
        if _R.storyboard.ebSetting().ebSettingRootViewController() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'ebSettingRootViewController' could not be loaded from storyboard 'EBSetting' as 'EBSettingRootViewController'.") }
      }

      fileprivate init() {}
    }
    #endif

    #if os(iOS) || os(tvOS)
    struct ebWeather: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = EBWeatherListViewController

      let bundle = R.hostingBundle
      let ebWeatherListViewController = StoryboardViewControllerResource<EBWeatherListViewController>(identifier: "EBWeatherListViewController")
      let name = "EBWeather"

      func ebWeatherListViewController(_: Void = ()) -> EBWeatherListViewController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: ebWeatherListViewController)
      }

      static func validate() throws {
        if UIKit.UIImage(named: "image/icon/general/gear", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'image/icon/general/gear' is used in storyboard 'EBWeather', but couldn't be loaded.") }
        if #available(iOS 11.0, tvOS 11.0, *) {
        }
        if _R.storyboard.ebWeather().ebWeatherListViewController() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'ebWeatherListViewController' could not be loaded from storyboard 'EBWeather' as 'EBWeatherListViewController'.") }
      }

      fileprivate init() {}
    }
    #endif

    #if os(iOS) || os(tvOS)
    struct launchScreen: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = UIKit.UIViewController

      let bundle = R.hostingBundle
      let name = "LaunchScreen"

      static func validate() throws {
        if #available(iOS 11.0, tvOS 11.0, *) {
        }
      }

      fileprivate init() {}
    }
    #endif

    fileprivate init() {}
  }
  #endif

  fileprivate init() {}
}
